apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dumbapi
  template:
    metadata:
      labels:
        app: dumbapi
    spec:
      containers:
      - name: dumbapi
        image: "glimap/dumbapi:4705e2c8c25bd37cd6685594a88411564a76a6c3"
        imagePullPolicy: { ? { .Values.image.pullPolicy } }
        ports:
        - name: http
          containerPort: { ? { .Values.service.port } }
          protocol: TCP
