apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dumbapi
  template:
    metadata:
      labels:
        app: dumbapi
    spec:
      containers:
      - name: dumbapi
        image: "glimap/dumbapi:4705e2c8c25bd37cd6685594a88411564a76a6c3"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
